"""change_phone_no_to_bigint

Revision ID: 402825d19354
Revises: da5a64090f12
Create Date: 2026-06-14 13:00:20.696383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402825d19354'
down_revision: Union[str, Sequence[str], None] = 'da5a64090f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone_no',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customers', 'phone_no',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
